spring:
  profiles:
    active: local


# local
---
spring:
  profiles: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false # File and Posts 시퀀스가 다른 번호로 올라가서 같은 번호로 올라가게 하기 위해 작성
  h2:
    console:
      enabled: true
      path: /h2-console
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
#server:
  #error:
   # include-exception: true
   # include-stacktrace: always
   # whitelabel:
   #   enabled: false